INSERT INTO farmacos (
  nome,
  unidade_padrao,
  concentracao_padrao,
  permite_dose_livre,
  ativo
) VALUES
  ('Acepromazina', NULL, NULL, 1, 1),
  ('Dexmedetomidina', NULL, NULL, 1, 1),
  ('Xilazina', NULL, NULL, 1, 1),
  ('Ketamina', NULL, NULL, 1, 1),
  ('Metadona', NULL, NULL, 1, 1),
  ('Morfina', NULL, NULL, 1, 1),
  ('Petidina', NULL, NULL, 1, 1),
  ('Tramadol', NULL, NULL, 1, 1),
  ('Propofol', NULL, NULL, 1, 1),
  ('Fentanil', NULL, NULL, 1, 1),
  ('Lidocaina', NULL, NULL, 1, 1),
  ('Isoflurano', NULL, NULL, 1, 1),
  ('Sevoflurano', NULL, NULL, 1, 1),
  ('Propofol TIVA', NULL, NULL, 1, 1),
  ('Dexmedetomidina CRI', NULL, NULL, 1, 1),
  ('Ketamina CRI', NULL, NULL, 1, 1),
  ('Lidocaina CRI', NULL, NULL, 1, 1),
  ('Fentanil CRI', NULL, NULL, 1, 1),
  ('Remifentanil CRI', NULL, NULL, 1, 1),
  ('Buprenorfina', NULL, NULL, 1, 1),
  ('Efedrina', NULL, NULL, 1, 1),
  ('Noradrenalina', NULL, NULL, 1, 1),
  ('Dopamina', NULL, NULL, 1, 1),
  ('Dobutamina', NULL, NULL, 1, 1),
  ('Fenilefrina', NULL, NULL, 1, 1),
  ('Adrenalina', NULL, NULL, 1, 1),
  ('Atropina', NULL, NULL, 1, 1),
  ('Glicopirrolato', NULL, NULL, 1, 1),
  ('Maropitant', NULL, NULL, 1, 1),
  ('Ondansetrona', NULL, NULL, 1, 1),
  ('Metoclopramida', NULL, NULL, 1, 1),
  ('Atipamezol', NULL, NULL, 1, 1),
  ('Ioimbina', NULL, NULL, 1, 1),
  ('Naloxona', NULL, NULL, 1, 1),
  ('Flumazenil', NULL, NULL, 1, 1),
  ('Dexametasona', NULL, NULL, 1, 1),
  ('Hidrocortisona', NULL, NULL, 1, 1),
  ('Gluconato de calcio', NULL, NULL, 1, 1),
  ('Bicarbonato de sodio', NULL, NULL, 1, 1);